## fetch API

fetch() promise는 HTTP error에 의해 reject 되지 않는다.

따로 에러처리를 해줘야한다?